//  SPECIFICSupplier  Screen

export const POSTSPECIFICSUPPLIERREQ = "POSTSPECIFICSUPPLIERREQ";
export const POSTSPECIFICSUPPLIERSUCESSS = "POSTSPECIFICSUPPLIERSUCESSS";
export const POSTSPECIFICSUPPLIERFailure = "POSTSPECIFICSUPPLIERFailure";


//  Get ALL Data

export const GETSPECIFICSUPPLIERREQ = "GETSPECIFICSUPPLIERREQ";
export const GETSPECIFICSUPPLIERSUCESSS = "GETSPECIFICSUPPLIERSUCESSS";
export const GETSPECIFICSUPPLIERFailure = "GETSPECIFICSUPPLIERFailure";

 
// Get  Single SPECIFICSupplier

export const GETSINGLEBYIDSPECIFICSUPPLIERDROPDOWNREQ = "GETSINGLEBYIDSPECIFICSUPPLIERDROPDOWNREQ";
export const GETSINGLEBYIDSPECIFICSUPPLIERDROPDOWNSUCESSS = "GETSINGLEBYIDSPECIFICSUPPLIERDROPDOWNSUCESSS";
export const GETSINGLEBYIDSPECIFICSUPPLIERDROPDOWNFailure = "GETSINGLEBYIDSPECIFICSUPPLIERDROPDOWNFailure";


// Action types for Edit
export const EDITUPDATESPECIFICSUPPLIERREQ = "EDITUPDATESPECIFICSUPPLIERREQ";
export const EDITUPDATESPECIFICSUPPLIERSUCCESS = "EDITUPDATESPECIFICSUPPLIERSUCCESS";
export const EDITUPDATESPECIFICSUPPLIERFAILURE = "EDITUPDATESPECIFICSUPPLIERFAILURE";




// Action types for Delete
export const DELETEITEMREQ = "DELETEITEMREQ";
export const DELETEITEMSUCCESS = "DELETEITEMSUCCESS";
export const DELETEITEMFAILURE = "DELETEITEMFAILURE";
