//  Master  Screen

//  Load Email ID in Dropdown
export const PAGEACESSEMAILDROPDOWNREQ = "PAGEACESSEMAILDROPDOWNREQ";
export const PAGEACESSEMAILDROPDOWNSUCESSS = "PAGEACESSEMAILDROPDOWNSUCESSS";
export const PAGEACESSEMAILDROPDOWNFailure = "PAGEACESSEMAILDROPDOWNFailure";

// : Load Menu Names in Table

export const PAGELISTSCREENREQ = "PAGELISTSCREENREQ";
export const PAGELISTSCREENSUCESSS = "PAGELISTSCREENSUCESSS";
export const PAGELISTSCREENFailure = "PAGELISTSCREENFailure";

// Load particular users menu list with check box checked
export const PAGELISTUSERACESSREQ = "PAGELISTUSERACESSREQ";
export const PAGELISTUSERACESSSUCESSS = "PAGELISTUSERACESSSUCESSS";
export const PAGELISTUSERACESSFailure = "PAGELISTUSERACESSFailure";

export const PAGECHECKSCREENREQ = "PAGECHECKSCREENREQ";
export const PAGECHECKSCREENSUCESSS = "PAGECHECKSCREENSUCESSS";
export const PAGECHECKSCREENFailure = "PAGECHECKSCREENFailure";

//  Updated  Acesss master

export const PAGEUPDATESSCREENREQ = "PAGECHECKSCREENREQ";
export const PAGEUPDATESSCREENSUCESSS = "PAGECHECKSCREENSUCESSS";
export const PAGEUPDATESSCREENFailure = "PAGECHECKSCREENFailure";
