
export const GETSUPPLIERREPORTSREQ = "GETSUPPLIERREPORTSREQ";
export const GETSUPPLIERREPORTSSUCESSS = "GETSUPPLIERREPORTSSUCESSS";
export const GETSUPPLIERREPORTSFailure = "GETSUPPLIERREPORTSFailure";


