//  GET ALL PAGE ACCESS Master  Screen

export const GETALLUSERSPAGEACCESSREQ = "GETALLUSERSPAGEACCESSREQ";
export const GETALLUSERSPAGEACCESSFAILURE = "GETALLUSERSPAGEACCESSFAILURE";
export const GETALLUSERSPAGEACCESSSUCCESS = "GETALLUSERSPAGEACCESSSUCCESS";

//  PUT UPDATE PAGE ACCESS

export const PUTUSERPAGEACCESSMASTERREQ = "PUTUSERPAGEACCESSMASTERREQ";
export const PUTUSERPAGEACCESSMASTERSUCCESS = "PUTUSERPAGEACCESSMASTERSUCCESS";
export const PUTUSERPAGEACCESSMASTERFAILURE = "PUTUSERPAGEACCESSMASTERFAILURE";


// Action types for Edit
export const EDITITEMREQ = "EDITITEMREQ";
export const EDITITEMSUCCESS = "EDITITEMSUCCESS";
export const EDITITEMFAILURE = "EDITITEMFAILURE";


// Action types for Delete
export const DELETEITEMREQ = "DELETEITEMREQ";
export const DELETEITEMSUCCESS = "DELETEITEMSUCCESS";
export const DELETEITEMFAILURE = "DELETEITEMFAILURE";
