//  Supplier  Screen

export const POSTSUPPLIERREQ = "POSTSUPPLIERREQ";
export const POSTSUPPLIERSUCESSS = "POSTSUPPLIERSUCESSS";
export const POSTSUPPLIERFailure = "POSTSUPPLIERFailure";


//  Get ALL Data

export const GETSUPPLIERREQ = "GETSUPPLIERREQ";
export const GETSUPPLIERSUCESSS = "GETSUPPLIERSUCESSS";
export const GETSUPPLIERFailure = "GETSUPPLIERFailure";

 
// Get  Single Supplier

export const GETSINGLEBYIDSUPPLIERREQ = "GETSINGLEBYIDSUPPLIERREQ";
export const GETSINGLEBYIDSUPPLIERSUCESSS = "GETSINGLEBYIDSUPPLIERSUCESSS";
export const GETSINGLEBYIDSUPPLIERFailure = "GETSINGLEBYIDSUPPLIERFailure";


// Action types for Edit
export const EDITUPDATESUPPLIERREQ = "EDITUPDATESUPPLIERREQ";
export const EDITUPDATESUPPLIERSUCCESS = "EDITUPDATESUPPLIERSUCCESS";
export const EDITUPDATESUPPLIERFAILURE = "EDITUPDATESUPPLIERFAILURE";




// Action types for Delete
export const DELETEITEMREQ = "DELETEITEMREQ";
export const DELETEITEMSUCCESS = "DELETEITEMSUCCESS";
export const DELETEITEMFAILURE = "DELETEITEMFAILURE";
