//  Master  Screen

export const POSTITEMSNAMEREQ = "POSTITEMSNAMEREQ";
export const POSTITEMSNAMESUCESSS = "POSTITEMSNAMESUCESSS";
export const POSTITEMSNAMEFailure = "POSTITEMSNAMEFailure";

//  Get

export const GETITEMSNAMEREQ = "GETITEMSNAMEREQ";
export const GETITEMSNAMESUCESSS = "GETITEMSNAMESUCESSS";
export const GETITEMSNAMEFailure = "GETITEMSNAMEFailure";


// Action types for Edit
export const EDITITEMREQ = "EDITITEMREQ";
export const EDITITEMSUCCESS = "EDITITEMSUCCESS";
export const EDITITEMFAILURE = "EDITITEMFAILURE";


// Action types for Delete
export const DELETEITEMREQ = "DELETEITEMREQ";
export const DELETEITEMSUCCESS = "DELETEITEMSUCCESS";
export const DELETEITEMFAILURE = "DELETEITEMFAILURE";
