export const LOGINREQ = "LOGINREQ";
export const LOGINSUCCESS = "LOGINSUCCESS";
export const LOGINFAILURE = "LOGINFAILURE";

export const LOGOUTREQ = "LOGOUTREQ";
export const LOGOUTSUCCESS = "LOGOUTSUCCESS";
export const LOGOUTFAILURE = "LOGOUTFAILURE";


export const SIGNUPREQ = "SIGNUPREQ";
export const SIGNUPSUCCESS = "SIGNUPSUCCESS";
export const SIGNUPFAILURE = "SIGNUPFAILURE";

export const LOGGEDUSERREQ = "LOGGEDUSERREQ";
export const LOGGEDUSERSUCCESS = "LOGGEDUSERSUCCESS";
export const LOGGEDUSERFAILURE = "LOGGEDUSERFAILURE";

export const LOGGEDUSERUPDATEREQ = "LOGGEDUSERUPDATEREQ";
export const LOGGEDUSERUPDATESUCCESS = "LOGGEDUSERUPDATESUCCESS";
export const LOGGEDUSERUPDATEFAILURE = "LOGGEDUSERUPDATEFAILURE";


export const FORGETUSERPASSWORDREQ = "FORGETUSERPASSWORDREQ";
export const FORGETUSERPASSWORDSUCCESS = "FORGETUSERPASSWORDSUCCESS";
export const FORGETUSERPASSWORDFAILURE = "FORGETUSERPASSWORDFAILURE";


export const PAGEACESSREQ = "PAGEACESSREQ";
export const PAGEACESSSUCCESS = "PAGEACESSSUCCESS";
export const PAGEACESSFAILURE = "PAGEACESSFAILURE";

export const PAGEUPDATEEMPLOYEEACESSREQ = "PAGEUPDATEEMPLOYEEACESSREQ";
export const PAGEUPDATEEMPLOYEEACESSSUCCESS = "PAGEUPDATEEMPLOYEEACESSSUCCESS";
export const PAGEUPDATEEMPLOYEEACESSFAILURE = "PAGEUPDATEEMPLOYEEACESSFAILURE";


// To Load menu list for logged in user

export const LOGGEDUSERMENULISTREQ = "LOGGEDUSERMENULISTREQ";
export const LOGGEDUSERMENULISTSUCCESS = "LOGGEDUSERMENULISTSUCCESS";
export const LOGGEDUSERMENULISTFAILURE = "LOGGEDUSERMENULISTFAILURE";
// Generate OTP 
export const GENERATEOTPREQ = "GENERATEOTPREQ";
export const GENERATEOTPSUCCESS = "GENERATEOTPSUCCESS";
export const GENERATEOTPFAILURE = "GENERATEOTPFAILURE";

// Reset Password with OTP
export const RESETPASSWORDWITHOTPREQ = "RESETPASSWORDWITHOTPREQ";
export const RESETPASSWORDWITHOTPSUCCESS = "RESETPASSWORDWITHOTPSUCCESS";
export const RESETPASSWORDWITHOTPFAILURE = "RESETPASSWORDWITHOTPFAILURE";

// Reset Password with OTP
export const GETDETAILSWITHOTPREQ = "GETDETAILSWITHOTPREQ";
export const GETDETAILSWITHOTPSUCCESS = "GETDETAILSWITHOTPSUCCESS";
export const GETDETAILSWITHOTPFAILURE = "GETDETAILSWITHOTPFAILURE";